# Generated by Django 4.1.10 on 2023-07-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.BigAutoField(db_column='BID', primary_key=True, serialize=False, verbose_name='Role id')),
                ('role_name', models.CharField(max_length=20, verbose_name='')),
                ('description', models.CharField(max_length=200, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('login', models.CharField(max_length=20, verbose_name='Login')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('user_id', models.BigAutoField(db_column='BID', primary_key=True, serialize=False, verbose_name='User id')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.roles')),
            ],
        ),
    ]
