# Generated by Django 4.1.10 on 2023-08-11 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulletJournals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='variant',
        ),
        migrations.AddField(
            model_name='journal',
            name='count_of_markers',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='journal',
            name='termins',
            field=models.DateField(default=datetime.date(2023, 8, 14)),
        ),
        migrations.AddField(
            model_name='journal',
            name='type',
            field=models.CharField(default='infinite', max_length=30),
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
