# Generated by Django 4.1.10 on 2023-08-19 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulletJournals', '0002_rename_user_journal_owner_remove_journal_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='termins',
            field=models.DateField(default=datetime.date(2023, 8, 22)),
        ),
    ]
