# Generated by Django 4.1.10 on 2023-09-11 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulletJournals', '0006_alter_journal_termins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='termins',
            field=models.DateField(default=datetime.date(2023, 9, 14)),
        ),
    ]
