# Generated by Django 4.1.10 on 2023-07-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='Blueprint name')),
                ('blueprints_id', models.BigAutoField(db_column='BID', primary_key=True, serialize=False, verbose_name='Blueprint id')),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Users.user', verbose_name='user_id')),
            ],
        ),
    ]
