# Generated by Django 4.1.10 on 2023-08-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JournalBlueprints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='max_count_of_markers',
            field=models.IntegerField(default=3),
        ),
    ]
