# Generated by Django 4.1.10 on 2023-08-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JournalBlueprints', '0002_blueprint_max_count_of_markers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='max_count_of_markers',
            field=models.IntegerField(default=3, verbose_name='Count of markers'),
        ),
    ]
